services:
  scylla_node:
    image: scylladb/scylla
    container_name: scylla_node
    command: |
      --smp 1
      --memory 1G
      --developer-mode 1
      --overprovisioned 1
      --alternator-write-isolation always
      --alternator-port 8000
    ports:
      - "9042:9042"
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "cqlsh", "127.0.0.1", "9042", "-e", "select * from system.local WHERE key='local'" ]
      interval: 5s
      timeout: 5s
      retries: 60
