services:
  scylla_node:
    image: scylladb/scylla
    container_name: scylla_node
    command: |
      --smp 1
      --memory 1G
      --developer-mode 1
      --overprovisioned 1
      --alternator-write-isolation always
      --alternator-port 8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -X POST http://localhost:8000/ -H 'X-Amz-Target: DynamoDB_20120810.DescribeLimits' -d '{}' -f || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 60
