services:
  scylla:
    image: scylladb/scylla
    container_name: scylla
    command: |
      --smp 1
      --memory 1G
      --developer-mode 1
      --overprovisioned 1
      --alternator-write-isolation always
      --listen-address 0.0.0.0
      --rpc-address 0.0.0.0
      --alternator-port 8000
    ports:
      - "9042:9042"
      - "8000:8000"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
